@isTest
private class TestAdobeCustomTypes  {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        AdobeCustomTypes obj = new AdobeCustomTypes ();
        AdobeCustomTypes.CommonResponse obj1 = new AdobeCustomTypes.CommonResponse();
        obj1.success = true;
        //obj1.resultType = resultTypeEnum.ID;
        obj1.resultMsg = 'test';
        
       
      }
        
        
    }